backend/config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

backend/app/models/snippet.rb
class Snippet < ApplicationRecord
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

backend/app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: %i[ show edit update destroy ]

  # GET /snippets or /snippets.json
  def index
    @snippets = Snippet.all
  end

  # GET /snippets/1 or /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets or /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to snippet_url(@snippet), notice: "Snippet was successfully created." }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1 or /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to snippet_url(@snippet), notice: "Snippet was successfully updated." }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1 or /snippets/1.json
  def destroy
    @snippet.destroy!

    respond_to do |format|
      format.html { redirect_to snippets_url, notice: "Snippet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def snippet_params
      params.require(:snippet).permit(:title, :language, :contents)
    end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/snippets_helper.rb
module SnippetsHelper
end

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackendT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/snippets/_form.html.erb
<%= form_with(model: snippet) do |form| %>
  <% if snippet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
        <% snippet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :language, style: "display: block" %>
    <%= form.text_field :language %>
  </div>

  <div>
    <%= form.label :contents, style: "display: block" %>
    <%= form.text_field :contents %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/snippets/_snippet.html.erb
<div id="<%= dom_id snippet %>">
  <p>
    <strong>Title:</strong>
    <%= snippet.title %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= snippet.language %>
  </p>

  <p>
    <strong>Contents:</strong>
    <%= snippet.contents %>
  </p>

</div>

backend/app/views/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= render "form", snippet: @snippet %>

<br>

<div>
  <%= link_to "Show this snippet", @snippet %> |
  <%= link_to "Back to snippets", snippets_path %>
</div>

backend/app/views/snippets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Snippets</h1>

<div id="snippets">
  <% @snippets.each do |snippet| %>
    <%= render snippet %>
    <p>
      <%= link_to "Show this snippet", snippet %>
    </p>
  <% end %>
</div>

<%= link_to "New snippet", new_snippet_path %>

backend/app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render "form", snippet: @snippet %>

<br>

<div>
  <%= link_to "Back to snippets", snippets_path %>
</div>

backend/app/views/snippets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @snippet %>

<div>
  <%= link_to "Edit this snippet", edit_snippet_path(@snippet) %> |
  <%= link_to "Back to snippets", snippets_path %>

  <%= button_to "Destroy this snippet", @snippet, method: :delete %>
</div>